# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4acbcacdb007064ddba9a4dde41a443788db3b5329e2bc46d2950057271f118e324003ce4cb85d98ac4f8c932a28d53c0a6d604c2c71f422076be07320c7d115

test:
  secret_key_base: 3d47a4bf4de81668baab348e03c7b55618cc399e7411b8640258bc190fa211ab224524c7b929e50f0e37107ab193dfb3f2bfca2d7d9f50db8d134fabca0c3b5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
